package com.finance.smartLedger.shared.util;

import static org.junit.jupiter.api.Assertions.*;

import java.util.UUID;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("UuidGenerator Tests")
class UuidGeneratorTest {

  @Test
  @DisplayName("Should generate random UUID")
  void shouldGenerateRandomUuid() {
    UUID uuid = UuidGenerator.generate();

    assertNotNull(uuid);
    assertNotEquals(UUID.randomUUID(), uuid);
  }

  @Test
  @DisplayName("Should generate UUID from string")
  void shouldGenerateUuidFromString() {
    String input = "test-input";
    UUID uuid1 = UuidGenerator.generateFromString(input);
    UUID uuid2 = UuidGenerator.generateFromString(input);

    assertNotNull(uuid1);
    assertEquals(uuid1, uuid2);
  }

  @Test
  @DisplayName("Should generate different UUIDs from different strings")
  void shouldGenerateDifferentUuidsFromDifferentStrings() {
    UUID uuid1 = UuidGenerator.generateFromString("input1");
    UUID uuid2 = UuidGenerator.generateFromString("input2");

    assertNotEquals(uuid1, uuid2);
  }

  @Test
  @DisplayName("Should generate UUID as string")
  void shouldGenerateUuidAsString() {
    String uuidString = UuidGenerator.generateAsString();

    assertNotNull(uuidString);
    assertFalse(uuidString.isEmpty());
    assertTrue(
        uuidString.matches("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"));
  }

  @Test
  @DisplayName("Should validate valid UUID string")
  void shouldValidateValidUuidString() {
    String validUuid = "550e8400-e29b-41d4-a716-446655440000";

    assertTrue(UuidGenerator.isValid(validUuid));
  }

  @Test
  @DisplayName("Should invalidate invalid UUID string")
  void shouldInvalidateInvalidUuidString() {
    String invalidUuid = "not-a-uuid";

    assertFalse(UuidGenerator.isValid(invalidUuid));
  }

  @Test
  @DisplayName("Should handle null UUID string gracefully")
  void shouldHandleNullUuidStringGracefully() {
    assertThrows(NullPointerException.class, () -> UuidGenerator.isValid(null));
  }

  @Test
  @DisplayName("Should invalidate empty UUID string")
  void shouldInvalidateEmptyUuidString() {
    assertFalse(UuidGenerator.isValid(""));
  }

  @Test
  @DisplayName("Should invalidate malformed UUID string")
  void shouldInvalidateMalformedUuidString() {
    String malformedUuid = "550e8400-e29b-41d4-a716";

    assertFalse(UuidGenerator.isValid(malformedUuid));
  }

  @Test
  @DisplayName("Should parse valid UUID string")
  void shouldParseValidUuidString() {
    String uuidString = "550e8400-e29b-41d4-a716-446655440000";
    UUID expected = UUID.fromString(uuidString);

    UUID result = UuidGenerator.parse(uuidString);

    assertEquals(expected, result);
  }

  @Test
  @DisplayName("Should throw exception when parsing invalid UUID string")
  void shouldThrowExceptionWhenParsingInvalidUuidString() {
    String invalidUuid = "not-a-uuid";

    assertThrows(IllegalArgumentException.class, () -> UuidGenerator.parse(invalidUuid));
  }

  @Test
  @DisplayName("Should generate unique UUIDs")
  void shouldGenerateUniqueUuids() {
    UUID uuid1 = UuidGenerator.generate();
    UUID uuid2 = UuidGenerator.generate();
    UUID uuid3 = UuidGenerator.generate();

    assertNotEquals(uuid1, uuid2);
    assertNotEquals(uuid2, uuid3);
    assertNotEquals(uuid1, uuid3);
  }

  @Test
  @DisplayName("Should generate unique UUID strings")
  void shouldGenerateUniqueUuidStrings() {
    String uuid1 = UuidGenerator.generateAsString();
    String uuid2 = UuidGenerator.generateAsString();
    String uuid3 = UuidGenerator.generateAsString();

    assertNotEquals(uuid1, uuid2);
    assertNotEquals(uuid2, uuid3);
    assertNotEquals(uuid1, uuid3);
  }

  @Test
  @DisplayName("Should handle UUID version 4 format")
  void shouldHandleUuidVersion4Format() {
    UUID uuid = UuidGenerator.generate();
    String uuidString = uuid.toString();

    assertTrue(
        uuidString.matches(
            "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"));
  }

  @Test
  @DisplayName("Should parse UUID generated by generate method")
  void shouldParseUuidGeneratedByGenerateMethod() {
    UUID uuid = UuidGenerator.generate();
    UUID parsed = UuidGenerator.parse(uuid.toString());

    assertEquals(uuid, parsed);
  }

  @Test
  @DisplayName("Should validate UUID generated by generateAsString method")
  void shouldValidateUuidGeneratedByGenerateAsStringMethod() {
    String uuidString = UuidGenerator.generateAsString();

    assertTrue(UuidGenerator.isValid(uuidString));
  }
}
